{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
    name: {{ data.get('name') }}
    version: {{ data.get('version') }}

build:
    number: 0
    string: py39
    script:
        - {{ PYTHON }} -m pip install -vv .

source:
    path: ..

requirements:
    host:
        - python >=3.8
        - cython
        - pip
    run:
        - lxml
        - requests
        - conda =4.14.0


about:
    home: https://github.com/yodeng/conda-local
    license: MIT
